version: '3'
services:
  web:
    image: "$IMAGE:Build-$BUILD_NUMBER"
    container_name: "web"
    build: .
    ports:
      - "80:80"
  redis:
    image: "redis:alpine"
    container_name: "db"
    command: --port 6380
    ports:
      - "6380:6380"
    expose:
      - "6380"
